SCALE = 0.5

X, Y = 3510 * SCALE, 1610 * SCALE

MENU_HEIGHT = 200
MENU_BORDER_THICKNESS = 10
STANDARD_BUTTON_WIDTH, STANDARD_BUTTON_HEIGTH = 150, 50

MENU_Y_OFFSET = Y+MENU_BORDER_THICKNESS
CONNECT_BUTTON_X, CONNECT_BUTTON_Y = STANDARD_BUTTON_WIDTH, Y+MENU_BORDER_THICKNESS

NETWORK_TABLE_NAME = "DrivingGUI"


