SCALE = 0.5

X, Y = 3510 * SCALE, 1610 * SCALE

MENU_HEIGHT = 200
MENU_BORDER_THICKNESS = 10

MODE_BUTTON_X, MODE_BUTTON_Y = 0, Y+MENU_BORDER_THICKNESS
MODE_BUTTON_WIDTH, MODE_BUTTON_HEIGHT = 150, 50


NETWORK_TABLE_NAME = "DrivingGUI"


